"""empty message

Revision ID: 620ef7a67b26
Revises: 5a741dac33e5
Create Date: 2020-09-04 20:32:59.104436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620ef7a67b26'
down_revision = '5a741dac33e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'is_publish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('is_publish', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
